### ISSUE TITLE
Scripts de bases de datos

### ISSUE THREAD

**Issue by jdbermeol** [saaperezru/iudex#4]
Lo que pasa es que los scrpts de bases de datos que estoy usando son los que están en el repositorio, esos como que están atrasados o al hacer un merge se eligió la version vieja porque sigue saliendo el error al votar, entonces para preguntar donde están los últimos scripts de base de datos y si p or favor alguien los puede colocar en el repositorio.

**Comment by saaperezru** [comment]
La última versión dle trunk corrige esto. Efectivamente se borró una parte del script durante el merge, pero no fue nada grave.

**Comment by saaperezru** [comment]
Otra tabla de ratings tenía el mismo problema. El commit 237cfd523758aebb352cc02cf8a1727ba36bc8c8 arregla todo esto.
